logging:
  file:
    name: ./logs/log-file.log
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8082
spring:
  profiles:
    default: '@activatedProperties@'
  application:
    name: files-service
management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
cadastroEmpresa:
  path: api/v1
  service:
    name: CADASTRO-SERVICE
