server:
  port: 8082
spring:
  application:
    name: files-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eureka.pollacontadores.com.br/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}