server:
  port: 8082
spring:
  profiles:
    default: '@activatedProperties@'
  application:
    name: files-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
graphMicrosoft:
  host: https://graph.microsoft.com
  tenant: v1.0/users/53b3f9ef-d92b-4ddb-b051-24e5acad1037
  service:
    name: MicrosoftGraph