server:
  port: 0
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://auth-service.cn0tlrtsmlxe.us-east-1.rds.amazonaws.com:5432/auth_service
    username: auth_service
    password: WsScXwfbbTL78xvT13xWs2Wtw7MrU78yLtkS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://bqujpfmacu.us-east-1.awsapprunner.com/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}