name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Build and Package Maven
        run: mvn clean package -DskipTests -B

      - name: Upload Artifact to s3
        run: |
            sudo apt-get install -y zip
            zip -r deployment.zip target/*.jar scripts/*.sh appspec.yml pom.xml
            aws s3 cp deployment.zip s3://${{ secrets.AWS_DEPLOY_BUCKET }}/
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }} 

    - run: |
        aws deploy create-deployment \
        --application-name FILES \
        --deployment-group-name GROUP-FILES \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --s3-location bucket=${{ secrets.AWS_DEPLOY_BUCKET }},key=deployment.zip,bundleType=zip  